AllCops:
  TargetRubyVersion: 2.6.3

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
    - 'testold/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'
    - 'testold/**/*'
    - 'lib/spark_components/element.rb'

Layout/TrailingBlankLines:
 EnforcedStyle: final_newline
 # Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'testold/tmp/app/components/baz/foobar_component.rb'

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'testold/dummy/bin/setup'
    - 'testold/dummy/bin/update'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/**/*.rb'
    - 'testold/**/*'

